### ISSUE TITLE
Install via package requires extra manual steps?

### ISSUE THREAD

**Issue by njsand** [psachin/insert-shebang#10]
[Readme.org](https://github.com/psachin/insert-shebang/blob/master/ReadMe.org) suggests that to install via a package, only  `M-x package-install RET insert-shebang RET` is necessary.  However, I found I still need to do `(add-hook 'find-file-hook 'insert-shebang)` to make everything work.

Is that supposed to be necessary after installation via a package?  If so, I think Readme.org needs to be clarified.

I am using emacs version 24.4.1.

**Comment by psachin** [comment]
Hi Nick,

Are you sure you need to `add-hook` after `package-install`? because I verified again and that is not needed.

Use add-hook only if you are performing manual install.

**Comment by njsand** [comment]
Yeah, I'm pretty sure that it's not working for me.

This is what I have tested:

1. Create a ~/.emacs containing only this:

    (require 'package)
    (add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/"))
    (package-initialize)

1. `rm -fr .emacs.d` just for good measure.  (That's where packages are stored when downloaded, right?)

1. Run `emacs`

1. M-x package-install insert-shebang

1. M-x find-file ~/myshellscript.sh

And no `#!/bin/bash` or something like that gets inserted.  I don't see `insert-shebang` in the hook variable.

Is there a different package source I should use?  (Apart from melpa?)

What is the mechanism that sets up `find-file-hook` when I install by a package?  To be honest when I look through `insert-shebang.el` I don't see how it will happen.

Thanks!

**Comment by njsand** [comment]
Oh, and I should mention that I'm using melpa because insert-shebang doesn't seem to be in the default elpa.gnu.org.

**Comment by psachin** [comment]
Hey, thanx Nick for pointing out the issue in the ReadMe. The ReadMe has been updated.

**Comment by psachin** [comment]
@njsand This is been fixed. Now you don't need to add the code

`(add-hook 'find-file-hook 'insert-shebang)` 

inside Emacs' init

---

If you get sometime, please do me a favour. I have automated a Emacs setup and installation:

[https://github.com/psachin/.emacs.d](https://github.com/psachin/.emacs.d)

Please try and give feedback/suggesstion
